### ISSUE TITLE
Is this published?

### ISSUE THREAD

**Issue by trg818** [milankl/CarbonFootprintAGU#23]
I think this pretty cool work. Is it "formally" published somewhere? If not, AGU's Eos Transactions seem like the obvious choice; at least they should be made aware of it for their weekly web digest. Same thing for Nature's daily Briefing newsletter.

**Comment by milankl** [comment]
A peer-reviewed manuscript is in preparation, including more discussion around the social aspects and the effects of the various reduction scenarios. Unlikely Eos, to leave the Geoscience bubble. Stay tuned ;) I haven't tried pushing it for daily/weekly newsletters, but you are welcome to spread the message!

**Comment by trg818** [comment]
Ok, I pointed Nature Briefing and Eos to it, let's see if they include it. At least with Nature Briefing, it would get out of the Geoscience bubble.

**Comment by milankl** [comment]
Amazing, thanks so much!
