### ISSUE TITLE
Why T divided by 1000?

### ISSUE THREAD

**Issue by yasergsi** [milankl/CarbonFootprintAGU#30]
Can you explain why in `calculate_emission.py` you divide T by 1000 in `line no. 27`. Why 1000?

**Comment by milankl** [comment]
The variable `T` is in kg of CO2e, to convert it to tonnes of CO2e it's divided by 1000 for the print statement
https://github.com/ConferenceCarbonTracker/CarbonFootprintAGU/blob/b4594a902a31ddc13f5032fb8d1b1a4255c56711/scripts/calculate_emissions.py#L18-L27

**Comment by yasergsi** [comment]
Ohhhkk, Thanks
